language: node_js
node_js:
  - "12.13"

script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

deploy:
  provider: npm
  edge: true
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
    
  on:
    repo: megahoneybadger/hsms

